# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 24ce1ae5d92e02e8293ad4cb5f18e850c0c4e7924dc8083a8e0ada208e3da712df298b165179db40d00f99fe6431cf0b0ab580371d7b06219697a82f20598d05

test:
  secret_key_base: 6ba750201b524e94a7b096f95b5178343b38e3991d7d881009e61981e0afe66a807b576bd925872e40d9e9522c407b40eac11873a175aa5a900b5f506f0fe4e7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
